[package]
name = "helix-ext"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]


# ///////////////// crate ignore

[dependencies.crossbeam-deque]
version = "0.8.3"

[dependencies.log]
version = "0.4.20"

[dependencies.memchr]
version = "2.6.3"



[dependencies.same-file]
version = "1.0.6"


[dependencies.aho-corasick]
version = "1.1.1"

[dependencies.bstr]
version = "1.6.2"
features = ["std"]
default-features = false
[dependencies.regex-automata]
version = "0.4.0"
features = [
    "std",
    "perf",
    "syntax",
    "meta",
    "nfa",
    "hybrid",
    "dfa-onepass",
]
default-features = false


[dependencies.regex-syntax]
version = "0.8.0"
features = ["std"]
default-features = false


[dependencies.ahash]
version = "0.8"

[dependencies.bumpalo]
version = "3.19"

[dependencies.bytes]
version = "1.10"

[dependencies.faststr]
version = "0.2"
features = ["serde"]

[dependencies.itoa]
version = "1.0"

[dependencies.ref-cast]
version = "1.0"

[dependencies.serde]
version = "1.0"
features = [
    "rc",
    "derive",
]

[dependencies.simdutf8]
version = "0.1"

[dependencies.sonic-number]
version = "0.1"

[dependencies.sonic-simd]
version = "0.1"

[dependencies.thiserror]
version = "2.0"

[dependencies.zmij]
version = "1.0"
