[package]
name = "helix-ext"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]


# ///////////////// crate ignore

[dependencies.crossbeam-deque]
version = "0.8.3"

[dependencies.globset]
version = "0.4.18"

[dependencies.log]
version = "0.4.20"

[dependencies.memchr]
version = "2.6.3"

[dependencies.regex-automata]
version = "0.4.0"
features = [
    "std",
    "perf",
    "syntax",
    "meta",
    "nfa",
    "hybrid",
    "dfa-onepass",
]
default-features = false

[dependencies.same-file]
version = "1.0.6"
